version : '3'

services :
  db :
    container_name : 'phongsaton-postgres'
    ports:
      - 54321:5432
    environment :
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    image : 'postgres:14.4'
    restart : 'unless-stopped'
  pgadmin :
    container_name : 'phongsaton-pgadmin'
    ports:
      - 8080:80
    environment :
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    image : 'dpage/pgadmin4:latest'
    restart : 'unless-stopped'
  strapi :
    container_name : 'phongsaton-strapi'
    ports:
      - 1337:1337
    environment :
      - DATABASE_CLIENT=${STARPI_DBCLIENT}
      - DATABASE_HOST=${STARPI_DBHOST}
      - DATABASE_PORT=${STARPI_DBPORT}
      - DATABASE_NAME=${STARPI_DBNAME}
      - DATABASE_USERNAME=${STARPI_DBUSERNAME}
      - DATABASE_PASSWORD=${STARPI_DBPASS}
      - DATABASE_SSL=false
    image : 'naskio/strapi:latest'
    restart : 'unless-stopped'
